<template>
  <div class="p-8">
    <div class="mb-8">
      <h2 class="text-2xl font-bold text-gray-900">Dashboard</h2>
      <p class="text-gray-500 mt-1">Real-time investment intelligence overview</p>
    </div>
    
    <!-- Stats Cards -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
      <div class="card">
        <p class="text-sm font-medium text-gray-500">Total Signals</p>
        <p class="text-3xl font-bold text-gray-900 mt-2">{{ stats.overview?.total_signals || 0 }}</p>
        <p class="text-xs text-green-600 mt-1">+{{ stats.overview?.signals_today || 0 }} today</p>
      </div>
      <div class="card">
        <p class="text-sm font-medium text-gray-500">Total Companies</p>
        <p class="text-3xl font-bold text-gray-900 mt-2">{{ stats.overview?.total_companies || 0 }}</p>
        <p class="text-xs text-green-600 mt-1">+{{ stats.overview?.companies_7d || 0 }} this week</p>
      </div>
      <div class="card">
        <p class="text-sm font-medium text-gray-500">DD Reports</p>
        <p class="text-3xl font-bold text-gray-900 mt-2">{{ stats.overview?.total_reports || 0 }}</p>
        <p class="text-xs text-gray-500 mt-1">Generated by 26 Agents</p>
      </div>
      <div class="card">
        <p class="text-sm font-medium text-gray-500">IC Meetings</p>
        <p class="text-3xl font-bold text-gray-900 mt-2">{{ stats.overview?.total_meetings || 0 }}</p>
        <p class="text-xs text-gray-500 mt-1">4 IC members + managers</p>
      </div>
    </div>
    
    <!-- Charts Row -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
      <!-- Sector Distribution -->
      <div class="card">
        <h3 class="text-lg font-semibold mb-4">By Sector</h3>
        <div class="space-y-3">
          <div v-for="s in stats.sectors" :key="s.name" class="flex items-center">
            <span class="text-sm w-20 truncate">{{ s.name }}</span>
            <div class="flex-1 mx-3 bg-gray-100 rounded-full h-2">
              <div
                class="bg-blue-500 h-2 rounded-full transition-all"
                :style="{ width: sectorPercent(s.count) + '%' }"
              ></div>
            </div>
            <span class="text-sm font-medium">{{ s.count }}</span>
          </div>
        </div>
      </div>
      
      <!-- Score Distribution -->
      <div class="card">
        <h3 class="text-lg font-semibold mb-4">IC Score Distribution</h3>
        <div class="space-y-3">
          <div class="flex items-center">
            <span class="text-sm w-24">Excellent (8-10)</span>
            <div class="flex-1 mx-3 bg-gray-100 rounded-full h-2">
              <div class="bg-green-500 h-2 rounded-full" :style="{ width: scorePercent('excellent_8_10') + '%' }"></div>
            </div>
            <span class="text-sm">{{ stats.score_distribution?.excellent_8_10 || 0 }}</span>
          </div>
          <div class="flex items-center">
            <span class="text-sm w-24">Good (6-8)</span>
            <div class="flex-1 mx-3 bg-gray-100 rounded-full h-2">
              <div class="bg-blue-500 h-2 rounded-full" :style="{ width: scorePercent('good_6_8') + '%' }"></div>
            </div>
            <span class="text-sm">{{ stats.score_distribution?.good_6_8 || 0 }}</span>
          </div>
          <div class="flex items-center">
            <span class="text-sm w-24">Average (4-6)</span>
            <div class="flex-1 mx-3 bg-gray-100 rounded-full h-2">
              <div class="bg-yellow-500 h-2 rounded-full" :style="{ width: scorePercent('average_4_6') + '%' }"></div>
            </div>
            <span class="text-sm">{{ stats.score_distribution?.average_4_6 || 0 }}</span>
          </div>
          <div class="flex items-center">
            <span class="text-sm w-24">Poor (0-4)</span>
            <div class="flex-1 mx-3 bg-gray-100 rounded-full h-2">
              <div class="bg-red-500 h-2 rounded-full" :style="{ width: scorePercent('poor_0_4') + '%' }"></div>
            </div>
            <span class="text-sm">{{ stats.score_distribution?.poor_0_4 || 0 }}</span>
          </div>
        </div>
      </div>
      
      <!-- IC Outcomes -->
      <div class="card">
        <h3 class="text-lg font-semibold mb-4">IC Outcomes</h3>
        <div class="space-y-3">
          <div v-for="(count, outcome) in stats.ic_outcomes" :key="outcome" class="flex items-center justify-between py-2 border-b border-gray-100 last:border-0">
            <span class="text-sm capitalize">{{ outcome }}</span>
            <span :class="outcomeBadgeClass(outcome)">{{ count }}</span>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Recent Activity -->
    <div class="card">
      <h3 class="text-lg font-semibold mb-4">Recent Activity</h3>
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead class="bg-gray-50">
            <tr>
              <th class="text-left px-4 py-3 font-medium text-gray-500">Type</th>
              <th class="text-left px-4 py-3 font-medium text-gray-500">Title</th>
              <th class="text-left px-4 py-3 font-medium text-gray-500">Details</th>
              <th class="text-left px-4 py-3 font-medium text-gray-500">Time</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100">
            <tr v-for="activity in activities.slice(0, 10)" :key="activity.time + activity.title" class="hover:bg-gray-50">
              <td class="px-4 py-3">
                <span :class="activityBadgeClass(activity.type)">{{ activity.type }}</span>
              </td>
              <td class="px-4 py-3 font-medium">{{ activity.title }}</td>
              <td class="px-4 py-3 text-gray-500">
                <span v-if="activity.sector">{{ activity.sector }}</span>
                <span v-if="activity.manager">Manager: {{ activity.manager }}</span>
                <span v-if="activity.score">Score: {{ activity.score }}</span>
              </td>
              <td class="px-4 py-3 text-gray-400 text-xs">{{ formatTime(activity.time) }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { getDashboardStats, getRecentActivity } from '@/api/client'

const stats = ref<any>({})
const activities = ref<any[]>([])
const loading = ref(true)

const totalCompanies = computed(() => stats.value.overview?.total_companies || 1)

function sectorPercent(count: number) {
  return Math.round((count / totalCompanies.value) * 100)
}

function scorePercent(key: string) {
  const total = Object.values(stats.value.score_distribution || {}).reduce((a: number, b: any) => a + (b || 0), 0)
  return total ? Math.round(((stats.value.score_distribution?.[key] || 0) / total) * 100) : 0
}

function outcomeBadgeClass(outcome: string) {
  const map: Record<string, string> = {
    proceed: 'badge-green',
    abandon: 'badge-red',
    table: 'badge-yellow',
    pending: 'badge-gray',
  }
  return `badge ${map[outcome] || 'badge-gray'}`
}

function activityBadgeClass(type: string) {
  const map: Record<string, string> = {
    signal: 'badge-blue',
    company: 'badge-green',
    ic_meeting: 'badge-yellow',
  }
  return `badge ${map[type] || 'badge-gray'}`
}

function formatTime(time: string) {
  if (!time) return '-'
  const d = new Date(time)
  return d.toLocaleString()
}

onMounted(async () => {
  try {
    const [statsRes, activityRes] = await Promise.all([
      getDashboardStats(),
      getRecentActivity(),
    ])
    stats.value = statsRes.data
    activities.value = activityRes.data.activities || []
  } catch (e) {
    console.error('Failed to load dashboard:', e)
  } finally {
    loading.value = false
  }
})
</script>
